// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Chat/Chat.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Chat
{

    /// <summary>Holder for reflection information generated from Chat/Chat.proto</summary>
    public static partial class ChatReflection
    {

        #region Descriptor
        /// <summary>File descriptor for Chat/Chat.proto</summary>
        public static pbr::FileDescriptor Descriptor
        {
            get { return descriptor; }
        }
        private static pbr::FileDescriptor descriptor;

        static ChatReflection()
        {
            byte[] descriptorData = global::System.Convert.FromBase64String(
                string.Concat(
                  "Cg9DaGF0L0NoYXQucHJvdG8aH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAu",
                  "cHJvdG8aD0NoYXQvVXNlci5wcm90byJVCgxDUmVzU2VuZENoYXQSEQoJc2Vu",
                  "ZGVyX2lkGAEgASgNEh0KBWVycm9yGAIgASgOMg4uU2VuZENoYXRFcnJvchIT",
                  "CgtjaGF0X21zZ19pZBgDIAEoDSJXCghDaGF0QmFzZRIcCgljaGF0X3R5cGUY",
                  "ASABKA4yCS5DaGF0VHlwZRItCgl0aW1lc3RhbXAYAiABKAsyGi5nb29nbGUu",
                  "cHJvdG9idWYuVGltZXN0YW1wInwKCVNDaGF0VGV4dBIeCgtzZW5kZXJfaW5m",
                  "bxgBIAEoCzIJLlVzZXJJbmZvEhwKCWNoYXRfYmFzZRgCIAEoCzIJLkNoYXRC",
                  "YXNlEg8KB3Jvb21faWQYAyABKA0SCwoDbXNnGAQgASgJEhMKC2NoYXRfbXNn",
                  "X2lkGAUgASgNIoABCglTQ2hhdEljb24SHgoLc2VuZGVyX2luZm8YASABKAsy",
                  "CS5Vc2VySW5mbxIcCgljaGF0X2Jhc2UYAiABKAsyCS5DaGF0QmFzZRIPCgdy",
                  "b29tX2lkGAMgASgNEg8KB2ljb25faWQYBCABKA0SEwoLY2hhdF9tc2dfaWQY",
                  "BSABKA0iawoNQ1JlY3ZDaGF0VGV4dBIeCgtzZW5kZXJfaW5mbxgBIAEoCzIJ",
                  "LlVzZXJJbmZvEhwKCWNoYXRfYmFzZRgCIAEoCzIJLkNoYXRCYXNlEg8KB3Jv",
                  "b21faWQYAyABKA0SCwoDbXNnGAQgASgJIm8KDUNSZWN2Q2hhdEljb24SHgoL",
                  "c2VuZGVyX2luZm8YASABKAsyCS5Vc2VySW5mbxIcCgljaGF0X2Jhc2UYAiAB",
                  "KAsyCS5DaGF0QmFzZRIPCgdyb29tX2lkGAMgASgNEg8KB2ljb25faWQYBCAB",
                  "KA0qSQoIQ2hhdFR5cGUSFQoRQ0hBVF9UWVBFX0lOVkFMSUQQABISCg5DSEFU",
                  "X1RZUEVfVEVYVBABEhIKDkNIQVRfVFlQRV9JQ09OEAIqtAEKDVNlbmRDaGF0",
                  "RXJyb3ISGwoXU0VORF9DSEFUX0VSUk9SX0lOVkFMSUQQABIbChdTRU5EX0NI",
                  "QVRfRVJST1JfU1VDQ0VTUxABEiAKHFNFTkRfQ0hBVF9FUlJPUl9OT19TVUNI",
                  "X1JPT00QAhIlCiFTRU5EX0NIQVRfRVJST1JfTk9UX01BVENIX1NFU1NJT04Q",
                  "AxIgChxTRU5EX0NIQVRfRVJST1JfUk9PTV9SRU1PVkVEEARCB6oCBENoYXRi",
                  "BnByb3RvMw=="));
            descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
                new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Chat.UserReflection.Descriptor, },
                new pbr::GeneratedClrTypeInfo(new[] { typeof(global::Chat.ChatType), typeof(global::Chat.SendChatError), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.CResSendChat), global::Chat.CResSendChat.Parser, new[]{ "SenderId", "Error", "ChatMsgId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.ChatBase), global::Chat.ChatBase.Parser, new[]{ "ChatType", "Timestamp" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.SChatText), global::Chat.SChatText.Parser, new[]{ "SenderInfo", "ChatBase", "RoomId", "Msg", "ChatMsgId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.SChatIcon), global::Chat.SChatIcon.Parser, new[]{ "SenderInfo", "ChatBase", "RoomId", "IconId", "ChatMsgId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.CRecvChatText), global::Chat.CRecvChatText.Parser, new[]{ "SenderInfo", "ChatBase", "RoomId", "Msg" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.CRecvChatIcon), global::Chat.CRecvChatIcon.Parser, new[]{ "SenderInfo", "ChatBase", "RoomId", "IconId" }, null, null, null, null)
                }));
        }
        #endregion

    }
    #region Enums
    public enum ChatType
    {
        [pbr::OriginalName("CHAT_TYPE_INVALID")] Invalid = 0,
        [pbr::OriginalName("CHAT_TYPE_TEXT")] Text = 1,
        [pbr::OriginalName("CHAT_TYPE_ICON")] Icon = 2,
    }

    public enum SendChatError
    {
        [pbr::OriginalName("SEND_CHAT_ERROR_INVALID")] Invalid = 0,
        [pbr::OriginalName("SEND_CHAT_ERROR_SUCCESS")] Success = 1,
        [pbr::OriginalName("SEND_CHAT_ERROR_NO_SUCH_ROOM")] NoSuchRoom = 2,
        [pbr::OriginalName("SEND_CHAT_ERROR_NOT_MATCH_SESSION")] NotMatchSession = 3,
        [pbr::OriginalName("SEND_CHAT_ERROR_ROOM_REMOVED")] RoomRemoved = 4,
    }

    #endregion

    #region Messages
    public sealed partial class CResSendChat : pb::IMessage<CResSendChat>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<CResSendChat> _parser = new pb::MessageParser<CResSendChat>(() => new CResSendChat());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<CResSendChat> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Chat.ChatReflection.Descriptor.MessageTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CResSendChat()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CResSendChat(CResSendChat other) : this()
        {
            senderId_ = other.senderId_;
            error_ = other.error_;
            chatMsgId_ = other.chatMsgId_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CResSendChat Clone()
        {
            return new CResSendChat(this);
        }

        /// <summary>Field number for the "sender_id" field.</summary>
        public const int SenderIdFieldNumber = 1;
        private uint senderId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint SenderId
        {
            get { return senderId_; }
            set
            {
                senderId_ = value;
            }
        }

        /// <summary>Field number for the "error" field.</summary>
        public const int ErrorFieldNumber = 2;
        private global::Chat.SendChatError error_ = global::Chat.SendChatError.Invalid;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Chat.SendChatError Error
        {
            get { return error_; }
            set
            {
                error_ = value;
            }
        }

        /// <summary>Field number for the "chat_msg_id" field.</summary>
        public const int ChatMsgIdFieldNumber = 3;
        private uint chatMsgId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint ChatMsgId
        {
            get { return chatMsgId_; }
            set
            {
                chatMsgId_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as CResSendChat);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(CResSendChat other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (SenderId != other.SenderId) return false;
            if (Error != other.Error) return false;
            if (ChatMsgId != other.ChatMsgId) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (SenderId != 0) hash ^= SenderId.GetHashCode();
            if (Error != global::Chat.SendChatError.Invalid) hash ^= Error.GetHashCode();
            if (ChatMsgId != 0) hash ^= ChatMsgId.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (SenderId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(SenderId);
      }
      if (Error != global::Chat.SendChatError.Invalid) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Error);
      }
      if (ChatMsgId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(ChatMsgId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (SenderId != 0)
            {
                output.WriteRawTag(8);
                output.WriteUInt32(SenderId);
            }
            if (Error != global::Chat.SendChatError.Invalid)
            {
                output.WriteRawTag(16);
                output.WriteEnum((int)Error);
            }
            if (ChatMsgId != 0)
            {
                output.WriteRawTag(24);
                output.WriteUInt32(ChatMsgId);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (SenderId != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SenderId);
            }
            if (Error != global::Chat.SendChatError.Invalid)
            {
                size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)Error);
            }
            if (ChatMsgId != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ChatMsgId);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(CResSendChat other)
        {
            if (other == null)
            {
                return;
            }
            if (other.SenderId != 0)
            {
                SenderId = other.SenderId;
            }
            if (other.Error != global::Chat.SendChatError.Invalid)
            {
                Error = other.Error;
            }
            if (other.ChatMsgId != 0)
            {
                ChatMsgId = other.ChatMsgId;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SenderId = input.ReadUInt32();
            break;
          }
          case 16: {
            Error = (global::Chat.SendChatError) input.ReadEnum();
            break;
          }
          case 24: {
            ChatMsgId = input.ReadUInt32();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            SenderId = input.ReadUInt32();
                            break;
                        }
                    case 16:
                        {
                            Error = (global::Chat.SendChatError)input.ReadEnum();
                            break;
                        }
                    case 24:
                        {
                            ChatMsgId = input.ReadUInt32();
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class ChatBase : pb::IMessage<ChatBase>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<ChatBase> _parser = new pb::MessageParser<ChatBase>(() => new ChatBase());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<ChatBase> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Chat.ChatReflection.Descriptor.MessageTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ChatBase()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ChatBase(ChatBase other) : this()
        {
            chatType_ = other.chatType_;
            timestamp_ = other.timestamp_ != null ? other.timestamp_.Clone() : null;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ChatBase Clone()
        {
            return new ChatBase(this);
        }

        /// <summary>Field number for the "chat_type" field.</summary>
        public const int ChatTypeFieldNumber = 1;
        private global::Chat.ChatType chatType_ = global::Chat.ChatType.Invalid;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Chat.ChatType ChatType
        {
            get { return chatType_; }
            set
            {
                chatType_ = value;
            }
        }

        /// <summary>Field number for the "timestamp" field.</summary>
        public const int TimestampFieldNumber = 2;
        private global::Google.Protobuf.WellKnownTypes.Timestamp timestamp_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Google.Protobuf.WellKnownTypes.Timestamp Timestamp
        {
            get { return timestamp_; }
            set
            {
                timestamp_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as ChatBase);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(ChatBase other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (ChatType != other.ChatType) return false;
            if (!object.Equals(Timestamp, other.Timestamp)) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (ChatType != global::Chat.ChatType.Invalid) hash ^= ChatType.GetHashCode();
            if (timestamp_ != null) hash ^= Timestamp.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (ChatType != global::Chat.ChatType.Invalid) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ChatType);
      }
      if (timestamp_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (ChatType != global::Chat.ChatType.Invalid)
            {
                output.WriteRawTag(8);
                output.WriteEnum((int)ChatType);
            }
            if (timestamp_ != null)
            {
                output.WriteRawTag(18);
                output.WriteMessage(Timestamp);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (ChatType != global::Chat.ChatType.Invalid)
            {
                size += 1 + pb::CodedOutputStream.ComputeEnumSize((int)ChatType);
            }
            if (timestamp_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timestamp);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(ChatBase other)
        {
            if (other == null)
            {
                return;
            }
            if (other.ChatType != global::Chat.ChatType.Invalid)
            {
                ChatType = other.ChatType;
            }
            if (other.timestamp_ != null)
            {
                if (timestamp_ == null)
                {
                    Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                }
                Timestamp.MergeFrom(other.Timestamp);
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ChatType = (global::Chat.ChatType) input.ReadEnum();
            break;
          }
          case 18: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            ChatType = (global::Chat.ChatType)input.ReadEnum();
                            break;
                        }
                    case 18:
                        {
                            if (timestamp_ == null)
                            {
                                Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
                            }
                            input.ReadMessage(Timestamp);
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class SChatText : pb::IMessage<SChatText>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<SChatText> _parser = new pb::MessageParser<SChatText>(() => new SChatText());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<SChatText> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Chat.ChatReflection.Descriptor.MessageTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SChatText()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SChatText(SChatText other) : this()
        {
            senderInfo_ = other.senderInfo_ != null ? other.senderInfo_.Clone() : null;
            chatBase_ = other.chatBase_ != null ? other.chatBase_.Clone() : null;
            roomId_ = other.roomId_;
            msg_ = other.msg_;
            chatMsgId_ = other.chatMsgId_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SChatText Clone()
        {
            return new SChatText(this);
        }

        /// <summary>Field number for the "sender_info" field.</summary>
        public const int SenderInfoFieldNumber = 1;
        private global::Chat.UserInfo senderInfo_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Chat.UserInfo SenderInfo
        {
            get { return senderInfo_; }
            set
            {
                senderInfo_ = value;
            }
        }

        /// <summary>Field number for the "chat_base" field.</summary>
        public const int ChatBaseFieldNumber = 2;
        private global::Chat.ChatBase chatBase_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Chat.ChatBase ChatBase
        {
            get { return chatBase_; }
            set
            {
                chatBase_ = value;
            }
        }

        /// <summary>Field number for the "room_id" field.</summary>
        public const int RoomIdFieldNumber = 3;
        private uint roomId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint RoomId
        {
            get { return roomId_; }
            set
            {
                roomId_ = value;
            }
        }

        /// <summary>Field number for the "msg" field.</summary>
        public const int MsgFieldNumber = 4;
        private string msg_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Msg
        {
            get { return msg_; }
            set
            {
                msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "chat_msg_id" field.</summary>
        public const int ChatMsgIdFieldNumber = 5;
        private uint chatMsgId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint ChatMsgId
        {
            get { return chatMsgId_; }
            set
            {
                chatMsgId_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as SChatText);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(SChatText other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (!object.Equals(SenderInfo, other.SenderInfo)) return false;
            if (!object.Equals(ChatBase, other.ChatBase)) return false;
            if (RoomId != other.RoomId) return false;
            if (Msg != other.Msg) return false;
            if (ChatMsgId != other.ChatMsgId) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (senderInfo_ != null) hash ^= SenderInfo.GetHashCode();
            if (chatBase_ != null) hash ^= ChatBase.GetHashCode();
            if (RoomId != 0) hash ^= RoomId.GetHashCode();
            if (Msg.Length != 0) hash ^= Msg.GetHashCode();
            if (ChatMsgId != 0) hash ^= ChatMsgId.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (senderInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SenderInfo);
      }
      if (chatBase_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChatBase);
      }
      if (RoomId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(RoomId);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Msg);
      }
      if (ChatMsgId != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(ChatMsgId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (senderInfo_ != null)
            {
                output.WriteRawTag(10);
                output.WriteMessage(SenderInfo);
            }
            if (chatBase_ != null)
            {
                output.WriteRawTag(18);
                output.WriteMessage(ChatBase);
            }
            if (RoomId != 0)
            {
                output.WriteRawTag(24);
                output.WriteUInt32(RoomId);
            }
            if (Msg.Length != 0)
            {
                output.WriteRawTag(34);
                output.WriteString(Msg);
            }
            if (ChatMsgId != 0)
            {
                output.WriteRawTag(40);
                output.WriteUInt32(ChatMsgId);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (senderInfo_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(SenderInfo);
            }
            if (chatBase_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChatBase);
            }
            if (RoomId != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RoomId);
            }
            if (Msg.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Msg);
            }
            if (ChatMsgId != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ChatMsgId);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(SChatText other)
        {
            if (other == null)
            {
                return;
            }
            if (other.senderInfo_ != null)
            {
                if (senderInfo_ == null)
                {
                    SenderInfo = new global::Chat.UserInfo();
                }
                SenderInfo.MergeFrom(other.SenderInfo);
            }
            if (other.chatBase_ != null)
            {
                if (chatBase_ == null)
                {
                    ChatBase = new global::Chat.ChatBase();
                }
                ChatBase.MergeFrom(other.ChatBase);
            }
            if (other.RoomId != 0)
            {
                RoomId = other.RoomId;
            }
            if (other.Msg.Length != 0)
            {
                Msg = other.Msg;
            }
            if (other.ChatMsgId != 0)
            {
                ChatMsgId = other.ChatMsgId;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (senderInfo_ == null) {
              SenderInfo = new global::Chat.UserInfo();
            }
            input.ReadMessage(SenderInfo);
            break;
          }
          case 18: {
            if (chatBase_ == null) {
              ChatBase = new global::Chat.ChatBase();
            }
            input.ReadMessage(ChatBase);
            break;
          }
          case 24: {
            RoomId = input.ReadUInt32();
            break;
          }
          case 34: {
            Msg = input.ReadString();
            break;
          }
          case 40: {
            ChatMsgId = input.ReadUInt32();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 10:
                        {
                            if (senderInfo_ == null)
                            {
                                SenderInfo = new global::Chat.UserInfo();
                            }
                            input.ReadMessage(SenderInfo);
                            break;
                        }
                    case 18:
                        {
                            if (chatBase_ == null)
                            {
                                ChatBase = new global::Chat.ChatBase();
                            }
                            input.ReadMessage(ChatBase);
                            break;
                        }
                    case 24:
                        {
                            RoomId = input.ReadUInt32();
                            break;
                        }
                    case 34:
                        {
                            Msg = input.ReadString();
                            break;
                        }
                    case 40:
                        {
                            ChatMsgId = input.ReadUInt32();
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class SChatIcon : pb::IMessage<SChatIcon>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<SChatIcon> _parser = new pb::MessageParser<SChatIcon>(() => new SChatIcon());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<SChatIcon> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Chat.ChatReflection.Descriptor.MessageTypes[3]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SChatIcon()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SChatIcon(SChatIcon other) : this()
        {
            senderInfo_ = other.senderInfo_ != null ? other.senderInfo_.Clone() : null;
            chatBase_ = other.chatBase_ != null ? other.chatBase_.Clone() : null;
            roomId_ = other.roomId_;
            iconId_ = other.iconId_;
            chatMsgId_ = other.chatMsgId_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SChatIcon Clone()
        {
            return new SChatIcon(this);
        }

        /// <summary>Field number for the "sender_info" field.</summary>
        public const int SenderInfoFieldNumber = 1;
        private global::Chat.UserInfo senderInfo_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Chat.UserInfo SenderInfo
        {
            get { return senderInfo_; }
            set
            {
                senderInfo_ = value;
            }
        }

        /// <summary>Field number for the "chat_base" field.</summary>
        public const int ChatBaseFieldNumber = 2;
        private global::Chat.ChatBase chatBase_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Chat.ChatBase ChatBase
        {
            get { return chatBase_; }
            set
            {
                chatBase_ = value;
            }
        }

        /// <summary>Field number for the "room_id" field.</summary>
        public const int RoomIdFieldNumber = 3;
        private uint roomId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint RoomId
        {
            get { return roomId_; }
            set
            {
                roomId_ = value;
            }
        }

        /// <summary>Field number for the "icon_id" field.</summary>
        public const int IconIdFieldNumber = 4;
        private uint iconId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint IconId
        {
            get { return iconId_; }
            set
            {
                iconId_ = value;
            }
        }

        /// <summary>Field number for the "chat_msg_id" field.</summary>
        public const int ChatMsgIdFieldNumber = 5;
        private uint chatMsgId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint ChatMsgId
        {
            get { return chatMsgId_; }
            set
            {
                chatMsgId_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as SChatIcon);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(SChatIcon other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (!object.Equals(SenderInfo, other.SenderInfo)) return false;
            if (!object.Equals(ChatBase, other.ChatBase)) return false;
            if (RoomId != other.RoomId) return false;
            if (IconId != other.IconId) return false;
            if (ChatMsgId != other.ChatMsgId) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (senderInfo_ != null) hash ^= SenderInfo.GetHashCode();
            if (chatBase_ != null) hash ^= ChatBase.GetHashCode();
            if (RoomId != 0) hash ^= RoomId.GetHashCode();
            if (IconId != 0) hash ^= IconId.GetHashCode();
            if (ChatMsgId != 0) hash ^= ChatMsgId.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (senderInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SenderInfo);
      }
      if (chatBase_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChatBase);
      }
      if (RoomId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(RoomId);
      }
      if (IconId != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(IconId);
      }
      if (ChatMsgId != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(ChatMsgId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (senderInfo_ != null)
            {
                output.WriteRawTag(10);
                output.WriteMessage(SenderInfo);
            }
            if (chatBase_ != null)
            {
                output.WriteRawTag(18);
                output.WriteMessage(ChatBase);
            }
            if (RoomId != 0)
            {
                output.WriteRawTag(24);
                output.WriteUInt32(RoomId);
            }
            if (IconId != 0)
            {
                output.WriteRawTag(32);
                output.WriteUInt32(IconId);
            }
            if (ChatMsgId != 0)
            {
                output.WriteRawTag(40);
                output.WriteUInt32(ChatMsgId);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (senderInfo_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(SenderInfo);
            }
            if (chatBase_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChatBase);
            }
            if (RoomId != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RoomId);
            }
            if (IconId != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(IconId);
            }
            if (ChatMsgId != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ChatMsgId);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(SChatIcon other)
        {
            if (other == null)
            {
                return;
            }
            if (other.senderInfo_ != null)
            {
                if (senderInfo_ == null)
                {
                    SenderInfo = new global::Chat.UserInfo();
                }
                SenderInfo.MergeFrom(other.SenderInfo);
            }
            if (other.chatBase_ != null)
            {
                if (chatBase_ == null)
                {
                    ChatBase = new global::Chat.ChatBase();
                }
                ChatBase.MergeFrom(other.ChatBase);
            }
            if (other.RoomId != 0)
            {
                RoomId = other.RoomId;
            }
            if (other.IconId != 0)
            {
                IconId = other.IconId;
            }
            if (other.ChatMsgId != 0)
            {
                ChatMsgId = other.ChatMsgId;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (senderInfo_ == null) {
              SenderInfo = new global::Chat.UserInfo();
            }
            input.ReadMessage(SenderInfo);
            break;
          }
          case 18: {
            if (chatBase_ == null) {
              ChatBase = new global::Chat.ChatBase();
            }
            input.ReadMessage(ChatBase);
            break;
          }
          case 24: {
            RoomId = input.ReadUInt32();
            break;
          }
          case 32: {
            IconId = input.ReadUInt32();
            break;
          }
          case 40: {
            ChatMsgId = input.ReadUInt32();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 10:
                        {
                            if (senderInfo_ == null)
                            {
                                SenderInfo = new global::Chat.UserInfo();
                            }
                            input.ReadMessage(SenderInfo);
                            break;
                        }
                    case 18:
                        {
                            if (chatBase_ == null)
                            {
                                ChatBase = new global::Chat.ChatBase();
                            }
                            input.ReadMessage(ChatBase);
                            break;
                        }
                    case 24:
                        {
                            RoomId = input.ReadUInt32();
                            break;
                        }
                    case 32:
                        {
                            IconId = input.ReadUInt32();
                            break;
                        }
                    case 40:
                        {
                            ChatMsgId = input.ReadUInt32();
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class CRecvChatText : pb::IMessage<CRecvChatText>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<CRecvChatText> _parser = new pb::MessageParser<CRecvChatText>(() => new CRecvChatText());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<CRecvChatText> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Chat.ChatReflection.Descriptor.MessageTypes[4]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CRecvChatText()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CRecvChatText(CRecvChatText other) : this()
        {
            senderInfo_ = other.senderInfo_ != null ? other.senderInfo_.Clone() : null;
            chatBase_ = other.chatBase_ != null ? other.chatBase_.Clone() : null;
            roomId_ = other.roomId_;
            msg_ = other.msg_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CRecvChatText Clone()
        {
            return new CRecvChatText(this);
        }

        /// <summary>Field number for the "sender_info" field.</summary>
        public const int SenderInfoFieldNumber = 1;
        private global::Chat.UserInfo senderInfo_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Chat.UserInfo SenderInfo
        {
            get { return senderInfo_; }
            set
            {
                senderInfo_ = value;
            }
        }

        /// <summary>Field number for the "chat_base" field.</summary>
        public const int ChatBaseFieldNumber = 2;
        private global::Chat.ChatBase chatBase_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Chat.ChatBase ChatBase
        {
            get { return chatBase_; }
            set
            {
                chatBase_ = value;
            }
        }

        /// <summary>Field number for the "room_id" field.</summary>
        public const int RoomIdFieldNumber = 3;
        private uint roomId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint RoomId
        {
            get { return roomId_; }
            set
            {
                roomId_ = value;
            }
        }

        /// <summary>Field number for the "msg" field.</summary>
        public const int MsgFieldNumber = 4;
        private string msg_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Msg
        {
            get { return msg_; }
            set
            {
                msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as CRecvChatText);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(CRecvChatText other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (!object.Equals(SenderInfo, other.SenderInfo)) return false;
            if (!object.Equals(ChatBase, other.ChatBase)) return false;
            if (RoomId != other.RoomId) return false;
            if (Msg != other.Msg) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (senderInfo_ != null) hash ^= SenderInfo.GetHashCode();
            if (chatBase_ != null) hash ^= ChatBase.GetHashCode();
            if (RoomId != 0) hash ^= RoomId.GetHashCode();
            if (Msg.Length != 0) hash ^= Msg.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (senderInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SenderInfo);
      }
      if (chatBase_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChatBase);
      }
      if (RoomId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(RoomId);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Msg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (senderInfo_ != null)
            {
                output.WriteRawTag(10);
                output.WriteMessage(SenderInfo);
            }
            if (chatBase_ != null)
            {
                output.WriteRawTag(18);
                output.WriteMessage(ChatBase);
            }
            if (RoomId != 0)
            {
                output.WriteRawTag(24);
                output.WriteUInt32(RoomId);
            }
            if (Msg.Length != 0)
            {
                output.WriteRawTag(34);
                output.WriteString(Msg);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (senderInfo_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(SenderInfo);
            }
            if (chatBase_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChatBase);
            }
            if (RoomId != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RoomId);
            }
            if (Msg.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Msg);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(CRecvChatText other)
        {
            if (other == null)
            {
                return;
            }
            if (other.senderInfo_ != null)
            {
                if (senderInfo_ == null)
                {
                    SenderInfo = new global::Chat.UserInfo();
                }
                SenderInfo.MergeFrom(other.SenderInfo);
            }
            if (other.chatBase_ != null)
            {
                if (chatBase_ == null)
                {
                    ChatBase = new global::Chat.ChatBase();
                }
                ChatBase.MergeFrom(other.ChatBase);
            }
            if (other.RoomId != 0)
            {
                RoomId = other.RoomId;
            }
            if (other.Msg.Length != 0)
            {
                Msg = other.Msg;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (senderInfo_ == null) {
              SenderInfo = new global::Chat.UserInfo();
            }
            input.ReadMessage(SenderInfo);
            break;
          }
          case 18: {
            if (chatBase_ == null) {
              ChatBase = new global::Chat.ChatBase();
            }
            input.ReadMessage(ChatBase);
            break;
          }
          case 24: {
            RoomId = input.ReadUInt32();
            break;
          }
          case 34: {
            Msg = input.ReadString();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 10:
                        {
                            if (senderInfo_ == null)
                            {
                                SenderInfo = new global::Chat.UserInfo();
                            }
                            input.ReadMessage(SenderInfo);
                            break;
                        }
                    case 18:
                        {
                            if (chatBase_ == null)
                            {
                                ChatBase = new global::Chat.ChatBase();
                            }
                            input.ReadMessage(ChatBase);
                            break;
                        }
                    case 24:
                        {
                            RoomId = input.ReadUInt32();
                            break;
                        }
                    case 34:
                        {
                            Msg = input.ReadString();
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class CRecvChatIcon : pb::IMessage<CRecvChatIcon>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<CRecvChatIcon> _parser = new pb::MessageParser<CRecvChatIcon>(() => new CRecvChatIcon());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<CRecvChatIcon> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Chat.ChatReflection.Descriptor.MessageTypes[5]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CRecvChatIcon()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CRecvChatIcon(CRecvChatIcon other) : this()
        {
            senderInfo_ = other.senderInfo_ != null ? other.senderInfo_.Clone() : null;
            chatBase_ = other.chatBase_ != null ? other.chatBase_.Clone() : null;
            roomId_ = other.roomId_;
            iconId_ = other.iconId_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public CRecvChatIcon Clone()
        {
            return new CRecvChatIcon(this);
        }

        /// <summary>Field number for the "sender_info" field.</summary>
        public const int SenderInfoFieldNumber = 1;
        private global::Chat.UserInfo senderInfo_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Chat.UserInfo SenderInfo
        {
            get { return senderInfo_; }
            set
            {
                senderInfo_ = value;
            }
        }

        /// <summary>Field number for the "chat_base" field.</summary>
        public const int ChatBaseFieldNumber = 2;
        private global::Chat.ChatBase chatBase_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Chat.ChatBase ChatBase
        {
            get { return chatBase_; }
            set
            {
                chatBase_ = value;
            }
        }

        /// <summary>Field number for the "room_id" field.</summary>
        public const int RoomIdFieldNumber = 3;
        private uint roomId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint RoomId
        {
            get { return roomId_; }
            set
            {
                roomId_ = value;
            }
        }

        /// <summary>Field number for the "icon_id" field.</summary>
        public const int IconIdFieldNumber = 4;
        private uint iconId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint IconId
        {
            get { return iconId_; }
            set
            {
                iconId_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as CRecvChatIcon);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(CRecvChatIcon other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (!object.Equals(SenderInfo, other.SenderInfo)) return false;
            if (!object.Equals(ChatBase, other.ChatBase)) return false;
            if (RoomId != other.RoomId) return false;
            if (IconId != other.IconId) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (senderInfo_ != null) hash ^= SenderInfo.GetHashCode();
            if (chatBase_ != null) hash ^= ChatBase.GetHashCode();
            if (RoomId != 0) hash ^= RoomId.GetHashCode();
            if (IconId != 0) hash ^= IconId.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (senderInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SenderInfo);
      }
      if (chatBase_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChatBase);
      }
      if (RoomId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(RoomId);
      }
      if (IconId != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(IconId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (senderInfo_ != null)
            {
                output.WriteRawTag(10);
                output.WriteMessage(SenderInfo);
            }
            if (chatBase_ != null)
            {
                output.WriteRawTag(18);
                output.WriteMessage(ChatBase);
            }
            if (RoomId != 0)
            {
                output.WriteRawTag(24);
                output.WriteUInt32(RoomId);
            }
            if (IconId != 0)
            {
                output.WriteRawTag(32);
                output.WriteUInt32(IconId);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (senderInfo_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(SenderInfo);
            }
            if (chatBase_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChatBase);
            }
            if (RoomId != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RoomId);
            }
            if (IconId != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(IconId);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(CRecvChatIcon other)
        {
            if (other == null)
            {
                return;
            }
            if (other.senderInfo_ != null)
            {
                if (senderInfo_ == null)
                {
                    SenderInfo = new global::Chat.UserInfo();
                }
                SenderInfo.MergeFrom(other.SenderInfo);
            }
            if (other.chatBase_ != null)
            {
                if (chatBase_ == null)
                {
                    ChatBase = new global::Chat.ChatBase();
                }
                ChatBase.MergeFrom(other.ChatBase);
            }
            if (other.RoomId != 0)
            {
                RoomId = other.RoomId;
            }
            if (other.IconId != 0)
            {
                IconId = other.IconId;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (senderInfo_ == null) {
              SenderInfo = new global::Chat.UserInfo();
            }
            input.ReadMessage(SenderInfo);
            break;
          }
          case 18: {
            if (chatBase_ == null) {
              ChatBase = new global::Chat.ChatBase();
            }
            input.ReadMessage(ChatBase);
            break;
          }
          case 24: {
            RoomId = input.ReadUInt32();
            break;
          }
          case 32: {
            IconId = input.ReadUInt32();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 10:
                        {
                            if (senderInfo_ == null)
                            {
                                SenderInfo = new global::Chat.UserInfo();
                            }
                            input.ReadMessage(SenderInfo);
                            break;
                        }
                    case 18:
                        {
                            if (chatBase_ == null)
                            {
                                ChatBase = new global::Chat.ChatBase();
                            }
                            input.ReadMessage(ChatBase);
                            break;
                        }
                    case 24:
                        {
                            RoomId = input.ReadUInt32();
                            break;
                        }
                    case 32:
                        {
                            IconId = input.ReadUInt32();
                            break;
                        }
                }
            }
        }
#endif

    }

    #endregion

}

#endregion Designer generated code