// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PacketBase.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ChatTest {

  /// <summary>Holder for reflection information generated from PacketBase.proto</summary>
  public static partial class PacketBaseReflection {

    #region Descriptor
    /// <summary>File descriptor for PacketBase.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PacketBaseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBQYWNrZXRCYXNlLnByb3RvKpwBCgpQYWNrZXRUeXBlEg0KCVBfSU5WQUxJ",
            "RBAAEhQKEFBfU19SZXFFbnRlclJvb20QARIRCg1QX1NfTGVhdmVSb29tEAIS",
            "DAoIUF9TX0NoYXQQAxIUChBQX0NfUmVzRW50ZXJSb29tEAQSEQoNUF9DX0xl",
            "YXZlUm9vbRAFEhEKDVBfQ19FbnRlclJvb20QBhIMCghQX0NfQ2hhdBAHQguq",
            "AghDaGF0VGVzdGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ChatTest.PacketType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum PacketType {
    [pbr::OriginalName("P_INVALID")] PInvalid = 0,
    [pbr::OriginalName("P_S_ReqEnterRoom")] PSReqEnterRoom = 1,
    [pbr::OriginalName("P_S_LeaveRoom")] PSLeaveRoom = 2,
    [pbr::OriginalName("P_S_Chat")] PSChat = 3,
    [pbr::OriginalName("P_C_ResEnterRoom")] PCResEnterRoom = 4,
    [pbr::OriginalName("P_C_LeaveRoom")] PCLeaveRoom = 5,
    [pbr::OriginalName("P_C_EnterRoom")] PCEnterRoom = 6,
    [pbr::OriginalName("P_C_Chat")] PCChat = 7,
  }

  #endregion

}

#endregion Designer generated code
