// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Chat.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Chat {

  /// <summary>Holder for reflection information generated from Chat.proto</summary>
  public static partial class ChatReflection {

    #region Descriptor
    /// <summary>File descriptor for Chat.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChatReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpDaGF0LnByb3RvGh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3Rv",
            "GgpVc2VyLnByb3RvIlcKCENoYXRCYXNlEhwKCWNoYXRfdHlwZRgBIAEoDjIJ",
            "LkNoYXRUeXBlEi0KCXRpbWVzdGFtcBgCIAEoCzIaLmdvb2dsZS5wcm90b2J1",
            "Zi5UaW1lc3RhbXAiWgoNU1NlbmRDaGF0VGV4dBIeCgtzZW5kZXJfaW5mbxgB",
            "IAEoCzIJLlVzZXJJbmZvEhwKCWNoYXRfYmFzZRgCIAEoCzIJLkNoYXRCYXNl",
            "EgsKA21zZxgDIAEoCSJeCg1TU2VuZENoYXRJY29uEh4KC3NlbmRlcl9pbmZv",
            "GAEgASgLMgkuVXNlckluZm8SHAoJY2hhdF9iYXNlGAIgASgLMgkuQ2hhdEJh",
            "c2USDwoHaWNvbl9pZBgDIAEoDSJaCg1DUmVjdkNoYXRUZXh0Eh4KC3NlbmRl",
            "cl9pbmZvGAEgASgLMgkuVXNlckluZm8SHAoJY2hhdF9iYXNlGAIgASgLMgku",
            "Q2hhdEJhc2USCwoDbXNnGAMgASgJIl4KDUNSZWN2Q2hhdEljb24SHgoLc2Vu",
            "ZGVyX2luZm8YASABKAsyCS5Vc2VySW5mbxIcCgljaGF0X2Jhc2UYAiABKAsy",
            "CS5DaGF0QmFzZRIPCgdpY29uX2lkGAMgASgNKkkKCENoYXRUeXBlEhUKEUNI",
            "QVRfVFlQRV9JTlZBTElEEAASEgoOQ0hBVF9UWVBFX1RFWFQQARISCg5DSEFU",
            "X1RZUEVfSUNPThACKmsKDVNlbmRDaGF0RXJyb3ISGwoXU0VORF9DSEFUX0VS",
            "Uk9SX0lOVkFMSUQQABIbChdTRU5EX0NIQVRfRVJST1JfU1VDQ0VTUxABEiAK",
            "HFNFTkRfQ0hBVF9FUlJPUl9ST09NX1JFTU9WRUQQAkIHqgIEQ2hhdGIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Chat.UserReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Chat.ChatType), typeof(global::Chat.SendChatError), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.ChatBase), global::Chat.ChatBase.Parser, new[]{ "ChatType", "Timestamp" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.SSendChatText), global::Chat.SSendChatText.Parser, new[]{ "SenderInfo", "ChatBase", "Msg" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.SSendChatIcon), global::Chat.SSendChatIcon.Parser, new[]{ "SenderInfo", "ChatBase", "IconId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.CRecvChatText), global::Chat.CRecvChatText.Parser, new[]{ "SenderInfo", "ChatBase", "Msg" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.CRecvChatIcon), global::Chat.CRecvChatIcon.Parser, new[]{ "SenderInfo", "ChatBase", "IconId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ChatType {
    [pbr::OriginalName("CHAT_TYPE_INVALID")] Invalid = 0,
    [pbr::OriginalName("CHAT_TYPE_TEXT")] Text = 1,
    [pbr::OriginalName("CHAT_TYPE_ICON")] Icon = 2,
  }

  public enum SendChatError {
    [pbr::OriginalName("SEND_CHAT_ERROR_INVALID")] Invalid = 0,
    [pbr::OriginalName("SEND_CHAT_ERROR_SUCCESS")] Success = 1,
    [pbr::OriginalName("SEND_CHAT_ERROR_ROOM_REMOVED")] RoomRemoved = 2,
  }

  #endregion

  #region Messages
  public sealed partial class ChatBase : pb::IMessage<ChatBase>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChatBase> _parser = new pb::MessageParser<ChatBase>(() => new ChatBase());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChatBase> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.ChatReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChatBase() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChatBase(ChatBase other) : this() {
      chatType_ = other.chatType_;
      timestamp_ = other.timestamp_ != null ? other.timestamp_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChatBase Clone() {
      return new ChatBase(this);
    }

    /// <summary>Field number for the "chat_type" field.</summary>
    public const int ChatTypeFieldNumber = 1;
    private global::Chat.ChatType chatType_ = global::Chat.ChatType.Invalid;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.ChatType ChatType {
      get { return chatType_; }
      set {
        chatType_ = value;
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChatBase);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChatBase other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ChatType != other.ChatType) return false;
      if (!object.Equals(Timestamp, other.Timestamp)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ChatType != global::Chat.ChatType.Invalid) hash ^= ChatType.GetHashCode();
      if (timestamp_ != null) hash ^= Timestamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ChatType != global::Chat.ChatType.Invalid) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ChatType);
      }
      if (timestamp_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ChatType != global::Chat.ChatType.Invalid) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ChatType);
      }
      if (timestamp_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ChatType != global::Chat.ChatType.Invalid) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ChatType);
      }
      if (timestamp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timestamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChatBase other) {
      if (other == null) {
        return;
      }
      if (other.ChatType != global::Chat.ChatType.Invalid) {
        ChatType = other.ChatType;
      }
      if (other.timestamp_ != null) {
        if (timestamp_ == null) {
          Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Timestamp.MergeFrom(other.Timestamp);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ChatType = (global::Chat.ChatType) input.ReadEnum();
            break;
          }
          case 18: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ChatType = (global::Chat.ChatType) input.ReadEnum();
            break;
          }
          case 18: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SSendChatText : pb::IMessage<SSendChatText>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SSendChatText> _parser = new pb::MessageParser<SSendChatText>(() => new SSendChatText());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SSendChatText> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.ChatReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SSendChatText() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SSendChatText(SSendChatText other) : this() {
      senderInfo_ = other.senderInfo_ != null ? other.senderInfo_.Clone() : null;
      chatBase_ = other.chatBase_ != null ? other.chatBase_.Clone() : null;
      msg_ = other.msg_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SSendChatText Clone() {
      return new SSendChatText(this);
    }

    /// <summary>Field number for the "sender_info" field.</summary>
    public const int SenderInfoFieldNumber = 1;
    private global::Chat.UserInfo senderInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.UserInfo SenderInfo {
      get { return senderInfo_; }
      set {
        senderInfo_ = value;
      }
    }

    /// <summary>Field number for the "chat_base" field.</summary>
    public const int ChatBaseFieldNumber = 2;
    private global::Chat.ChatBase chatBase_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.ChatBase ChatBase {
      get { return chatBase_; }
      set {
        chatBase_ = value;
      }
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int MsgFieldNumber = 3;
    private string msg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Msg {
      get { return msg_; }
      set {
        msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SSendChatText);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SSendChatText other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(SenderInfo, other.SenderInfo)) return false;
      if (!object.Equals(ChatBase, other.ChatBase)) return false;
      if (Msg != other.Msg) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (senderInfo_ != null) hash ^= SenderInfo.GetHashCode();
      if (chatBase_ != null) hash ^= ChatBase.GetHashCode();
      if (Msg.Length != 0) hash ^= Msg.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (senderInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SenderInfo);
      }
      if (chatBase_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChatBase);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Msg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (senderInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SenderInfo);
      }
      if (chatBase_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChatBase);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Msg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (senderInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SenderInfo);
      }
      if (chatBase_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChatBase);
      }
      if (Msg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Msg);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SSendChatText other) {
      if (other == null) {
        return;
      }
      if (other.senderInfo_ != null) {
        if (senderInfo_ == null) {
          SenderInfo = new global::Chat.UserInfo();
        }
        SenderInfo.MergeFrom(other.SenderInfo);
      }
      if (other.chatBase_ != null) {
        if (chatBase_ == null) {
          ChatBase = new global::Chat.ChatBase();
        }
        ChatBase.MergeFrom(other.ChatBase);
      }
      if (other.Msg.Length != 0) {
        Msg = other.Msg;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (senderInfo_ == null) {
              SenderInfo = new global::Chat.UserInfo();
            }
            input.ReadMessage(SenderInfo);
            break;
          }
          case 18: {
            if (chatBase_ == null) {
              ChatBase = new global::Chat.ChatBase();
            }
            input.ReadMessage(ChatBase);
            break;
          }
          case 26: {
            Msg = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (senderInfo_ == null) {
              SenderInfo = new global::Chat.UserInfo();
            }
            input.ReadMessage(SenderInfo);
            break;
          }
          case 18: {
            if (chatBase_ == null) {
              ChatBase = new global::Chat.ChatBase();
            }
            input.ReadMessage(ChatBase);
            break;
          }
          case 26: {
            Msg = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SSendChatIcon : pb::IMessage<SSendChatIcon>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SSendChatIcon> _parser = new pb::MessageParser<SSendChatIcon>(() => new SSendChatIcon());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SSendChatIcon> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.ChatReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SSendChatIcon() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SSendChatIcon(SSendChatIcon other) : this() {
      senderInfo_ = other.senderInfo_ != null ? other.senderInfo_.Clone() : null;
      chatBase_ = other.chatBase_ != null ? other.chatBase_.Clone() : null;
      iconId_ = other.iconId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SSendChatIcon Clone() {
      return new SSendChatIcon(this);
    }

    /// <summary>Field number for the "sender_info" field.</summary>
    public const int SenderInfoFieldNumber = 1;
    private global::Chat.UserInfo senderInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.UserInfo SenderInfo {
      get { return senderInfo_; }
      set {
        senderInfo_ = value;
      }
    }

    /// <summary>Field number for the "chat_base" field.</summary>
    public const int ChatBaseFieldNumber = 2;
    private global::Chat.ChatBase chatBase_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.ChatBase ChatBase {
      get { return chatBase_; }
      set {
        chatBase_ = value;
      }
    }

    /// <summary>Field number for the "icon_id" field.</summary>
    public const int IconIdFieldNumber = 3;
    private uint iconId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint IconId {
      get { return iconId_; }
      set {
        iconId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SSendChatIcon);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SSendChatIcon other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(SenderInfo, other.SenderInfo)) return false;
      if (!object.Equals(ChatBase, other.ChatBase)) return false;
      if (IconId != other.IconId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (senderInfo_ != null) hash ^= SenderInfo.GetHashCode();
      if (chatBase_ != null) hash ^= ChatBase.GetHashCode();
      if (IconId != 0) hash ^= IconId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (senderInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SenderInfo);
      }
      if (chatBase_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChatBase);
      }
      if (IconId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(IconId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (senderInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SenderInfo);
      }
      if (chatBase_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChatBase);
      }
      if (IconId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(IconId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (senderInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SenderInfo);
      }
      if (chatBase_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChatBase);
      }
      if (IconId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(IconId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SSendChatIcon other) {
      if (other == null) {
        return;
      }
      if (other.senderInfo_ != null) {
        if (senderInfo_ == null) {
          SenderInfo = new global::Chat.UserInfo();
        }
        SenderInfo.MergeFrom(other.SenderInfo);
      }
      if (other.chatBase_ != null) {
        if (chatBase_ == null) {
          ChatBase = new global::Chat.ChatBase();
        }
        ChatBase.MergeFrom(other.ChatBase);
      }
      if (other.IconId != 0) {
        IconId = other.IconId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (senderInfo_ == null) {
              SenderInfo = new global::Chat.UserInfo();
            }
            input.ReadMessage(SenderInfo);
            break;
          }
          case 18: {
            if (chatBase_ == null) {
              ChatBase = new global::Chat.ChatBase();
            }
            input.ReadMessage(ChatBase);
            break;
          }
          case 24: {
            IconId = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (senderInfo_ == null) {
              SenderInfo = new global::Chat.UserInfo();
            }
            input.ReadMessage(SenderInfo);
            break;
          }
          case 18: {
            if (chatBase_ == null) {
              ChatBase = new global::Chat.ChatBase();
            }
            input.ReadMessage(ChatBase);
            break;
          }
          case 24: {
            IconId = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CRecvChatText : pb::IMessage<CRecvChatText>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CRecvChatText> _parser = new pb::MessageParser<CRecvChatText>(() => new CRecvChatText());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CRecvChatText> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.ChatReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CRecvChatText() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CRecvChatText(CRecvChatText other) : this() {
      senderInfo_ = other.senderInfo_ != null ? other.senderInfo_.Clone() : null;
      chatBase_ = other.chatBase_ != null ? other.chatBase_.Clone() : null;
      msg_ = other.msg_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CRecvChatText Clone() {
      return new CRecvChatText(this);
    }

    /// <summary>Field number for the "sender_info" field.</summary>
    public const int SenderInfoFieldNumber = 1;
    private global::Chat.UserInfo senderInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.UserInfo SenderInfo {
      get { return senderInfo_; }
      set {
        senderInfo_ = value;
      }
    }

    /// <summary>Field number for the "chat_base" field.</summary>
    public const int ChatBaseFieldNumber = 2;
    private global::Chat.ChatBase chatBase_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.ChatBase ChatBase {
      get { return chatBase_; }
      set {
        chatBase_ = value;
      }
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int MsgFieldNumber = 3;
    private string msg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Msg {
      get { return msg_; }
      set {
        msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CRecvChatText);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CRecvChatText other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(SenderInfo, other.SenderInfo)) return false;
      if (!object.Equals(ChatBase, other.ChatBase)) return false;
      if (Msg != other.Msg) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (senderInfo_ != null) hash ^= SenderInfo.GetHashCode();
      if (chatBase_ != null) hash ^= ChatBase.GetHashCode();
      if (Msg.Length != 0) hash ^= Msg.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (senderInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SenderInfo);
      }
      if (chatBase_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChatBase);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Msg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (senderInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SenderInfo);
      }
      if (chatBase_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChatBase);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Msg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (senderInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SenderInfo);
      }
      if (chatBase_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChatBase);
      }
      if (Msg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Msg);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CRecvChatText other) {
      if (other == null) {
        return;
      }
      if (other.senderInfo_ != null) {
        if (senderInfo_ == null) {
          SenderInfo = new global::Chat.UserInfo();
        }
        SenderInfo.MergeFrom(other.SenderInfo);
      }
      if (other.chatBase_ != null) {
        if (chatBase_ == null) {
          ChatBase = new global::Chat.ChatBase();
        }
        ChatBase.MergeFrom(other.ChatBase);
      }
      if (other.Msg.Length != 0) {
        Msg = other.Msg;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (senderInfo_ == null) {
              SenderInfo = new global::Chat.UserInfo();
            }
            input.ReadMessage(SenderInfo);
            break;
          }
          case 18: {
            if (chatBase_ == null) {
              ChatBase = new global::Chat.ChatBase();
            }
            input.ReadMessage(ChatBase);
            break;
          }
          case 26: {
            Msg = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (senderInfo_ == null) {
              SenderInfo = new global::Chat.UserInfo();
            }
            input.ReadMessage(SenderInfo);
            break;
          }
          case 18: {
            if (chatBase_ == null) {
              ChatBase = new global::Chat.ChatBase();
            }
            input.ReadMessage(ChatBase);
            break;
          }
          case 26: {
            Msg = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CRecvChatIcon : pb::IMessage<CRecvChatIcon>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CRecvChatIcon> _parser = new pb::MessageParser<CRecvChatIcon>(() => new CRecvChatIcon());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CRecvChatIcon> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.ChatReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CRecvChatIcon() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CRecvChatIcon(CRecvChatIcon other) : this() {
      senderInfo_ = other.senderInfo_ != null ? other.senderInfo_.Clone() : null;
      chatBase_ = other.chatBase_ != null ? other.chatBase_.Clone() : null;
      iconId_ = other.iconId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CRecvChatIcon Clone() {
      return new CRecvChatIcon(this);
    }

    /// <summary>Field number for the "sender_info" field.</summary>
    public const int SenderInfoFieldNumber = 1;
    private global::Chat.UserInfo senderInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.UserInfo SenderInfo {
      get { return senderInfo_; }
      set {
        senderInfo_ = value;
      }
    }

    /// <summary>Field number for the "chat_base" field.</summary>
    public const int ChatBaseFieldNumber = 2;
    private global::Chat.ChatBase chatBase_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.ChatBase ChatBase {
      get { return chatBase_; }
      set {
        chatBase_ = value;
      }
    }

    /// <summary>Field number for the "icon_id" field.</summary>
    public const int IconIdFieldNumber = 3;
    private uint iconId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint IconId {
      get { return iconId_; }
      set {
        iconId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CRecvChatIcon);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CRecvChatIcon other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(SenderInfo, other.SenderInfo)) return false;
      if (!object.Equals(ChatBase, other.ChatBase)) return false;
      if (IconId != other.IconId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (senderInfo_ != null) hash ^= SenderInfo.GetHashCode();
      if (chatBase_ != null) hash ^= ChatBase.GetHashCode();
      if (IconId != 0) hash ^= IconId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (senderInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SenderInfo);
      }
      if (chatBase_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChatBase);
      }
      if (IconId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(IconId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (senderInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SenderInfo);
      }
      if (chatBase_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChatBase);
      }
      if (IconId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(IconId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (senderInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SenderInfo);
      }
      if (chatBase_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChatBase);
      }
      if (IconId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(IconId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CRecvChatIcon other) {
      if (other == null) {
        return;
      }
      if (other.senderInfo_ != null) {
        if (senderInfo_ == null) {
          SenderInfo = new global::Chat.UserInfo();
        }
        SenderInfo.MergeFrom(other.SenderInfo);
      }
      if (other.chatBase_ != null) {
        if (chatBase_ == null) {
          ChatBase = new global::Chat.ChatBase();
        }
        ChatBase.MergeFrom(other.ChatBase);
      }
      if (other.IconId != 0) {
        IconId = other.IconId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (senderInfo_ == null) {
              SenderInfo = new global::Chat.UserInfo();
            }
            input.ReadMessage(SenderInfo);
            break;
          }
          case 18: {
            if (chatBase_ == null) {
              ChatBase = new global::Chat.ChatBase();
            }
            input.ReadMessage(ChatBase);
            break;
          }
          case 24: {
            IconId = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (senderInfo_ == null) {
              SenderInfo = new global::Chat.UserInfo();
            }
            input.ReadMessage(SenderInfo);
            break;
          }
          case 18: {
            if (chatBase_ == null) {
              ChatBase = new global::Chat.ChatBase();
            }
            input.ReadMessage(ChatBase);
            break;
          }
          case 24: {
            IconId = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
